### ISSUE TITLE
这个项目的原始训练/测试数据还有么

### ISSUE THREAD

**Issue by caperea** [shuangge-jb/sklearn#1]
同学你好，请问这个项目的原始训练/测试数据还有么？我现在也在研究垃圾短信判断和机器学习的相关方法，感觉这个比赛的项目很有意思，但是这个数据现在在网上已经找不到了，不知道您这边还有没有，能不能分享一下呢？

**Comment by shuangge-jb** [comment]
http://pan.baidu.com/share/link?shareid=3552966806&uk=3040516006

**Comment by caperea** [comment]
感谢🙏
